import Image from "next/image"
import { ArrowUpRight, Github } from "lucide-react"

const projects = [
  { title: "TriageAI", description: "AI-powered CI failure triage for quickly diagnosing build and test failures, finding similar past incidents, and generating actionable issue drafts.", image: "/images/triage-ai.png", link: "https://github.com/androodo/TriageAI", tech: ["Python", "LangChain", "OpenAI", "RAG", "Embeddings", "CI/CD"] },
  { title: "R'Mart", description: "Built a university exclusive secondhand marketplace with 500+ users. Implemented JWT authentication, real-time messaging with WebSockets, listing recommendations, and search functionality. Hardened and scaled with encryption, Redis caching and rate limits, and protections for XSS, CSRF, DDoS, and SQL injection. Added AI search using Meilisearch plus OpenAI embeddings for fuzzy match and autocomplete.", image: "/images/rmart-logo.png", link: "https://github.com/androodo/R-mart", tech: ["React", "Node.js", "Express", "PostgreSQL", "AWS", "Docker", "Redis", "WebSockets"] },
  { title: "AI Song Remixer", description: "An AI-powered web application that takes an MP3 song, separates it into vocal and instrumental stems, applies a style transfer effect (Lofi, Jazz, or Dubstep) to the instrumental, and then merges the vocals back in to produce a remixed version of the original song.", image: "/images/ai-song-remixer.png", link: "https://github.com/androodo/AI-Song-Remixer", tech: ["Python", "PyTorch", "Demucs", "Librosa", "React", "Flask"] },
  { title: "CardSense", description: "Built a full-stack financial management platform that optimizes credit card rewards and tracks budgets, helping users maximize cashback by up to 25% on everyday purchases. Developed a Django REST API with 45+ endpoints for transaction processing and budget analytics. Implemented CSV import functionality reducing manual transaction entry time by 80%, with a React frontend that processes 1000+ transactions per user with sub-second response times.", image: "/images/cardsense-logo.png", link: "https://github.com/androodo/CardSense", tech: ["Python", "Django", "React", "TypeScript", "Tailwind CSS", "PostgreSQL", "Pandas", "scikit-learn"] },
  { title: "Highlander Health", description: "Built a full-stack nutrition website offering custom daily meal plans based on UCR Dining Hall menus. Developed a Python/Flask backend with OpenAI GPT API for real-time data analysis. Employed Beautiful Soup to scrape daily cafeteria menus and harnessed Pandas for thorough data cleaning, delivering personalized nutrition guidance to over 100 UCR students.", image: "/images/ucr-bear.png", link: "https://github.com/androodo/HighlanderHealth", tech: ["Python", "Flask", "OpenAI GPT", "Beautiful Soup", "Pandas"] },
  { title: "LocaInsight", description: "Built a full-stack travel application that generates personalized itineraries with comprehensive data validation, seamless third-party API integration, robust caching mechanisms, and optimized response times. Added robust error handling and response caching to improve reliability and reduce API response time by 20%.", image: "/images/globe.jpeg", link: "https://github.com/androodo/LocaInsight", tech: ["React", "Node.js", "Express", "Google Maps API", "Axios", "OpenAI GPT"] },
  { title: "Soccer Score Predictor", description: "Developed a robust machine learning application to predict soccer match outcomes with a 15% improvement in prediction accuracy by leveraging comprehensive historical player statistics and detailed team performance data. Designed a user-friendly web interface for real-time prediction display with configurable visualization options.", image: "/images/soccer-20ball.jpeg", link: "https://github.com/androodo/Soccer-Score-Predictor", tech: ["Python", "scikit-learn", "Pandas", "HTML", "CSS", "JavaScript"] },
]

export default function Projects() {
  return <section id="projects" className="py-24"><div className="mx-auto max-w-7xl px-4 md:px-6">
    <div className="mb-12 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="section-label mb-3">selected_work/</p><h2 className="section-title text-4xl font-bold tracking-tight md:text-5xl">Projects</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">A selection of products across fintech, AI, marketplaces, health, and machine learning.</p></div>
    <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
      {projects.map((project, index) => <article key={project.title} className={`group glass-panel flex min-h-full flex-col overflow-hidden rounded-2xl transition-all duration-300 hover:-translate-y-1 hover:border-primary/60 ${index < 2 ? "lg:col-span-1" : ""}`}>
        <a href={project.link} target="_blank" rel="noopener noreferrer" aria-label={`View ${project.title} on GitHub`} className="relative block aspect-[16/10] overflow-hidden bg-secondary">
          <Image src={project.image} alt={`${project.title} project image`} fill sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-105" />
          <div className="absolute inset-x-0 top-0 flex items-center justify-between p-4"><span className="rounded-md border border-border/70 bg-background/85 px-2 py-1 font-mono text-xs text-primary backdrop-blur">PROJECT_0{index + 1}</span><span className="grid size-10 place-items-center rounded-full border border-border bg-background/85 text-foreground backdrop-blur transition-colors group-hover:border-primary group-hover:bg-primary group-hover:text-primary-foreground"><ArrowUpRight className="size-4" /></span></div>
        </a>
        <div className="flex flex-1 flex-col p-6"><h3 className="text-2xl font-bold tracking-tight text-foreground transition-colors group-hover:text-primary">{project.title}</h3><p className="mt-3 line-clamp-4 text-sm leading-relaxed text-muted-foreground">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tech.map((tech) => <span key={tech} className="rounded-md border border-border bg-secondary/70 px-2.5 py-1 font-mono text-[11px] font-medium text-muted-foreground transition-colors hover:border-primary/50 hover:text-primary">{tech}</span>)}</div><a href={project.link} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 self-start text-sm font-semibold text-primary hover:text-accent"><Github className="size-4" />View source <ArrowUpRight className="size-3.5" /></a></div>
      </article>)}
    </div>
  </div></section>
}
